export const CHANGE_PAGE_INDEX = "CHANGE_PAGE_INDEX";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const SET_SHIPMENT_DETAILS = "SET_SHIPMENT_DETAILS";
